# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Login to Private Harbor
      uses: docker/login-action@v2
      with:
        registry: harbor.hsyhhssyy.net
        username: hsyhhssyy@example.com
        password: ${{ secrets.HARBOR_PUSH_KEY }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: true
        tags: harbor.hsyhhssyy.net/home-esxi/amiyabot-player-rating-standalone:latest, harbor.hsyhhssyy.net/home-esxi/amiyabot-player-rating-standalone:${{ github.sha }}
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      id: install
    - name: Write Context
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.HOMECLOUD_KUBECONFIG }}
      id: setcontext
    - name: Push to k8s
      uses: Azure/k8s-deploy@v4
      with:
        namespace: amiya-bot
        manifests: pod.yaml
        images: |
          harbor.hsyhhssyy.net/home-esxi/amiyabot-player-rating-standalone:${{ github.sha }}
        imagepullsecrets: harbor.hsyhhssyy.net